services:
    app-prod:
        image: money-keeper-server/prod:${TAG:-latest}
        build: .
        ports:
            - '${APP_PORT}:${APP_PORT}'
        env_file:
            - .env
        restart: unless-stopped
        deploy:
            mem_limit: 2g # Set max memory to 2 GB
            cpus: 2 # Set max CPU to 2 CPU core
