-- Categories V1
INSERT INTO icons (name, url, type) VALUES
('CHI_10_cong_viec', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_10_cong_viec.png', 'Expense V1'),
('CHI_10_dau_tu', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_10_dau_tu.png', 'Expense V1'),
('CHI_10_dich_vu_sinh_hoat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_10_dich_vu_sinh_hoat.png', 'Expense V1'),
('CHI_10_di_vay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_10_di_vay.png', 'Expense V1'),
('CHI_11_di_chuyen', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_11_di_chuyen.png', 'Expense V1'),
('CHI_11_gui_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_11_gui_xe.png', 'Expense V1'),
('CHI_11_oto', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_11_oto.png', 'Expense V1'),
('CHI_11_rua_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_11_rua_xe.png', 'Expense V1'),
('CHI_11_taxi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_11_taxi.png', 'Expense V1'),
('CHI_11_xe_tai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_11_xe_tai.png', 'Expense V1'),
('CHI_12_bus', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_12_bus.png', 'Expense V1'),
('CHI_12_du_lich', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_12_du_lich.png', 'Expense V1'),
('CHI_12_xang_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_12_xang_xe.png', 'Expense V1'),
('CHI_12_xe_dap', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_12_xe_dap.png', 'Expense V1'),
('CHI_12_xe_may', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_12_xe_may.png', 'Expense V1'),
('CHI_13_di_cho', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_13_di_cho.png', 'Expense V1'),
('CHI_13_giay_dep', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_13_giay_dep.png', 'Expense V1'),
('CHI_13_phim_ca_nhac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_13_phim_ca_nhac.png', 'Expense V1'),
('CHI_13_phu_kien_khac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_13_phu_kien_khac.png', 'Expense V1'),
('CHI_13_quan_ao', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_13_quan_ao.png', 'Expense V1'),
('CHI_13_trang_phuc', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_13_trang_phuc.png', 'Expense V1'),
('CHI_14_cavat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_14_cavat.png', 'Expense V1'),
('CHI_14_my_pham', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_14_my_pham.png', 'Expense V1'),
('CHI_15_dien_thoai_co_din', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_15_dien_thoai_co_din.png', 'Expense V1'),
('CHI_15_dien_thoai_di_dong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_15_dien_thoai_di_dong.png', 'Expense V1'),
('CHI_15_may_anh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_15_may_anh.png', 'Expense V1'),
('CHI_15_truyen_hinh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_15_truyen_hinh.png', 'Expense V1'),
('CHI_15_vui_choi_giai_tri', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_15_vui_choi_giai_tri.png', 'Expense V1'),
('CHI_16_do_choi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_16_do_choi.png', 'Expense V1'),
('CHI_16_karaoke', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_16_karaoke.png', 'Expense V1'),
('CHI_17_dien', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_17_dien.png', 'Expense V1'),
('CHI_17_mua_sam_do_dac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_17_mua_sam_do_dac.png', 'Expense V1'),
('CHI_17_tu_lanh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_17_tu_lanh.png', 'Expense V1'),
('CHI_18_may_giat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_18_may_giat.png', 'Expense V1'),
('CHI_19_gas', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_19_gas.png', 'Expense V1'),
('CHI_19_nuoc', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_19_nuoc.png', 'Expense V1'),
('CHI_1_an_tiem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_1_an_tiem.png', 'Expense V1'),
('CHI_1_an_uong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_1_an_uong.png', 'Expense V1'),
('CHI_1_an_vat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_1_an_vat.png', 'Expense V1'),
('CHI_1_bar', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_1_bar.png', 'Expense V1'),
('CHI_1_beer', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_1_beer.png', 'Expense V1'),
('CHI_1_cafe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_1_cafe.png', 'Expense V1'),
('CHI_1_kem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_1_kem.png', 'Expense V1'),
('CHI_1_lien_hoan', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_1_lien_hoan.png', 'Expense V1'),
('CHI_20_lam_dep', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_20_lam_dep.png', 'Expense V1'),
('CHI_20_spa', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_20_spa.png', 'Expense V1'),
('CHI_21_huong_thu', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_21_huong_thu.png', 'Expense V1'),
('CHI_21_thuong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_21_thuong.png', 'Expense V1'),
('CHI_21_tinh_yeu', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_21_tinh_yeu.png', 'Expense V1'),
('CHI_22_internet', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_22_internet.png', 'Expense V1'),
('CHI_22_the_thao', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_22_the_thao.png', 'Expense V1'),
('CHI_2_ban_be', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_ban_be.png', 'Expense V1'),
('CHI_2_concai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_concai.png', 'Expense V1'),
('CHI_2_cuoi_xin', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_cuoi_xin.png', 'Expense V1'),
('CHI_2_giao_luu_quan_he', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_giao_luu_quan_he.png', 'Expense V1'),
('CHI_2_nguoi_giup_viec', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_nguoi_giup_viec.png', 'Expense V1'),
('CHI_2_phat_trien_ban_than', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_phat_trien_ban_than.png', 'Expense V1'),
('CHI_2_tham_hoi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_tham_hoi.png', 'Expense V1'),
('CHI_2_trong_tre', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_trong_tre.png', 'Expense V1'),
('CHI_2_vui_choi_con_cai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_vui_choi_con_cai.png', 'Expense V1'),
('CHI_2_yoga', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_2_yoga.png', 'Expense V1'),
('CHI_3_bao_hiem_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_3_bao_hiem_xe.png', 'Expense V1'),
('CHI_3_bao_hiem_y_te', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_3_bao_hiem_y_te.png', 'Expense V1'),
('CHI_3_the', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_3_the.png', 'Expense V1'),
('CHI_4_lai_tiet_kiem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_4_lai_tiet_kiem.png', 'Expense V1'),
('CHI_4_sua_chua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_4_sua_chua.png', 'Expense V1'),
('CHI_4_sua_chua_nha_cua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_4_sua_chua_nha_cua.png', 'Expense V1'),
('CHI_5_bieu_tang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_5_bieu_tang.png', 'Expense V1'),
('CHI_5_dung_cu_hoc_tap', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_5_dung_cu_hoc_tap.png', 'Expense V1'),
('CHI_5_duoc_cho_tang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_5_duoc_cho_tang.png', 'Expense V1'),
('CHI_5_hieu_hi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_5_hieu_hi.png', 'Expense V1'),
('CHI_5_hoc_hanh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_5_hoc_hanh.png', 'Expense V1'),
('CHI_5_hoc_phi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_5_hoc_phi.png', 'Expense V1'),
('CHI_5_ngoai_khoa', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_5_ngoai_khoa.png', 'Expense V1'),
('CHI_5_sach_vo', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_5_sach_vo.png', 'Expense V1'),
('CHI_6_kham_chua_benh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_6_kham_chua_benh.png', 'Expense V1'),
('CHI_6_sua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_6_sua.png', 'Expense V1'),
('CHI_6_suc_khoe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_6_suc_khoe.png', 'Expense V1'),
('CHI_6_thuoc_men', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_6_thuoc_men.png', 'Expense V1'),
('CHI_7_cho_vay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_7_cho_vay.png', 'Expense V1'),
('CHI_7_luong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_7_luong.png', 'Expense V1'),
('CHI_7_thu_no', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_7_thu_no.png', 'Expense V1'),
('CHI_7_tien_lai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_7_tien_lai.png', 'Expense V1'),
('CHI_7_tien_tieu_vat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_7_tien_tieu_vat.png', 'Expense V1'),
('CHI_7_tra_no', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_7_tra_no.png', 'Expense V1'),
('CHI_8_thue_nha', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_8_thue_nha.png', 'Expense V1'),
('CHI_99_cho', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_99_cho.png', 'Expense V1'),
('CHI_99_meo', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_99_meo.png', 'Expense V1'),
('CHI_99_thu_cung', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_99_thu_cung.png', 'Expense V1'),
('CHI_99_tiet_kiem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_99_tiet_kiem.png', 'Expense V1'),
('CHI_99_vat_nuoi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_99_vat_nuoi.png', 'Expense V1'),
('CHI_9_gia_dinh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_9_gia_dinh.png', 'Expense V1'),
('CHI_9_khach_san', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_9_khach_san.png', 'Expense V1'),
('CHI_9_ngan_hang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_9_ngan_hang.png', 'Expense V1'),
('CHI_9_nha_cua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_9_nha_cua.png', 'Expense V1'),
('CHI_9_the_chap', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_9_the_chap.png', 'Expense V1'),
('CHI_an_sang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_an_sang.png', 'Expense V1'),
('CHI_an_toi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_an_toi.png', 'Expense V1'),
('CHI_an_trua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_an_trua.png', 'Expense V1'),
('CHI_chuyen_khoan', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_chuyen_khoan.png', 'Expense V1'),
('CHI_khac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_khac.png', 'Expense V1'),
('CHI_ma_chay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_ma_chay.png', 'Expense V1'),
('CHI_ngan_hang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_ngan_hang.png', 'Expense V1'),
('CHI_phi_chuyen_khoan', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_phi_chuyen_khoan.png', 'Expense V1'),
('CHI_UnKnow', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/CHI/CHI_UnKnow.png', 'Expense V1'),
('THU_bao_hiem_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_bao_hiem_xe.png', 'Income V1'),
('THU_bao_hiem_y_te', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_bao_hiem_y_te.png', 'Income V1'),
('THU_bieu_tang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_bieu_tang.png', 'Income V1'),
('THU_cho_vay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_cho_vay.png', 'Income V1'),
('THU_dau_tu', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_dau_tu.png', 'Income V1'),
('THU_dich_vu_sinh_hoat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_dich_vu_sinh_hoat.png', 'Income V1'),
('THU_di_vay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_di_vay.png', 'Income V1'),
('THU_duoc_cho_tang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_duoc_cho_tang.png', 'Income V1'),
('THU_hieu_hi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_hieu_hi.png', 'Income V1'),
('THU_hoc_phi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_hoc_phi.png', 'Income V1'),
('THU_khac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_khac.png', 'Income V1'),
('THU_lai_tiet_kiem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_lai_tiet_kiem.png', 'Income V1'),
('THU_luong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_luong.png', 'Income V1'),
('THU_nha_cua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_nha_cua.png', 'Income V1'),
('THU_rua_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_rua_xe.png', 'Income V1'),
('THU_sinh_hoat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_sinh_hoat.png', 'Income V1'),
('THU_the', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_the.png', 'Income V1'),
('THU_the_chap', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_the_chap.png', 'Income V1'),
('THU_thue_nha', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_thue_nha.png', 'Income V1'),
('THU_thuong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_thuong.png', 'Income V1'),
('THU_thu_no', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_thu_no.png', 'Income V1'),
('THU_tien_lai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_tien_lai.png', 'Income V1'),
('THU_tien_tieu_vat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_tien_tieu_vat.png', 'Income V1'),
('THU_tra_no', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_tra_no.png', 'Income V1'),
('THU_UnKnow', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V1/THU/THU_UnKnow.png', 'Income V1');

-- Categories V2
INSERT INTO icons (name, url, type)
VALUES              
('UnKnow', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/UnKnow.png', ''),
('CHI_10_cong_viec', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_10_cong_viec.png', 'Expense V2'),
('CHI_10_dau_tu', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_10_dau_tu.png', 'Expense V2'),
('CHI_10_dich_vu_sinh_hoat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_10_dich_vu_sinh_hoat.png', 'Expense V2'),
('CHI_10_di_vay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_10_di_vay.png', 'Expense V2'),
('CHI_11_di_chuyen', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_11_di_chuyen.png', 'Expense V2'),
('CHI_11_gui_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_11_gui_xe.png', 'Expense V2'),
('CHI_11_oto', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_11_oto.png', 'Expense V2'),
('CHI_11_rua_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_11_rua_xe.png', 'Expense V2'),
('CHI_11_taxi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_11_taxi.png', 'Expense V2'),
('CHI_11_xe_tai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_11_xe_tai.png', 'Expense V2'),
('CHI_12_bus', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_12_bus.png', 'Expense V2'),
('CHI_12_du_lich', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_12_du_lich.png', 'Expense V2'),
('CHI_12_xang_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_12_xang_xe.png', 'Expense V2'),
('CHI_12_xe_dap', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_12_xe_dap.png', 'Expense V2'),
('CHI_12_xe_may', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_12_xe_may.png', 'Expense V2'),
('CHI_13_di_cho', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_13_di_cho.png', 'Expense V2'),
('CHI_13_giay_dep', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_13_giay_dep.png', 'Expense V2'),
('CHI_13_phim_ca_nhac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_13_phim_ca_nhac.png', 'Expense V2'),
('CHI_13_phu_kien_khac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_13_phu_kien_khac.png', 'Expense V2'),
('CHI_13_quan_ao', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_13_quan_ao.png', 'Expense V2'),
('CHI_13_trang_phuc', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_13_trang_phuc.png', 'Expense V2'),
('CHI_14_cavat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_14_cavat.png', 'Expense V2'),
('CHI_14_my_pham', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_14_my_pham.png', 'Expense V2'),
('CHI_15_dien_thoai_co_din', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_15_dien_thoai_co_din.png', 'Expense V2'),
('CHI_15_dien_thoai_di_dong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_15_dien_thoai_di_dong.png', 'Expense V2'),
('CHI_15_may_anh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_15_may_anh.png', 'Expense V2'),
('CHI_15_truyen_hinh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_15_truyen_hinh.png', 'Expense V2'),
('CHI_15_vui_choi_giai_tri', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_15_vui_choi_giai_tri.png', 'Expense V2'),
('CHI_16_do_choi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_16_do_choi.png', 'Expense V2'),
('CHI_16_karaoke', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_16_karaoke.png', 'Expense V2'),
('CHI_17_dien', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_17_dien.png', 'Expense V2'),
('CHI_17_mua_sam_do_dac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_17_mua_sam_do_dac.png', 'Expense V2'),
('CHI_17_tu_lanh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_17_tu_lanh.png', 'Expense V2'),
('CHI_18_may_giat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_18_may_giat.png', 'Expense V2'),
('CHI_19_gas', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_19_gas.png', 'Expense V2'),
('CHI_19_nuoc', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_19_nuoc.png', 'Expense V2'),
('CHI_1_an_tiem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_1_an_tiem.png', 'Expense V2'),
('CHI_1_an_uong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_1_an_uong.png', 'Expense V2'),
('CHI_1_an_vat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_1_an_vat.png', 'Expense V2'),
('CHI_1_bar', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_1_bar.png', 'Expense V2'),
('CHI_1_beer', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_1_beer.png', 'Expense V2'),
('CHI_1_cafe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_1_cafe.png', 'Expense V2'),
('CHI_1_kem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_1_kem.png', 'Expense V2'),
('CHI_1_lien_hoan', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_1_lien_hoan.png', 'Expense V2'),
('CHI_20_lam_dep', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_20_lam_dep.png', 'Expense V2'),
('CHI_20_spa', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_20_spa.png', 'Expense V2'),
('CHI_21_huong_thu', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_21_huong_thu.png', 'Expense V2'),
('CHI_21_thuong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_21_thuong.png', 'Expense V2'),
('CHI_21_tinh_yeu', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_21_tinh_yeu.png', 'Expense V2'),
('CHI_22_internet', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_22_internet.png', 'Expense V2'),
('CHI_22_the_thao', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_22_the_thao.png', 'Expense V2'),
('CHI_2_ban_be', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_ban_be.png', 'Expense V2'),
('CHI_2_concai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_concai.png', 'Expense V2'),
('CHI_2_cuoi_xin', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_cuoi_xin.png', 'Expense V2'),
('CHI_2_giao_luu_quan_he', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_giao_luu_quan_he.png', 'Expense V2'),
('CHI_2_nguoi_giup_viec', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_nguoi_giup_viec.png', 'Expense V2'),
('CHI_2_phat_trien_ban_than', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_phat_trien_ban_than.png', 'Expense V2'),
('CHI_2_tham_hoi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_tham_hoi.png', 'Expense V2'),
('CHI_2_trong_tre', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_trong_tre.png', 'Expense V2'),
('CHI_2_vui_choi_con_cai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_vui_choi_con_cai.png', 'Expense V2'),
('CHI_2_yoga', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_2_yoga.png', 'Expense V2'),
('CHI_3_bao_hiem_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_3_bao_hiem_xe.png', 'Expense V2'),
('CHI_3_bao_hiem_y_te', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_3_bao_hiem_y_te.png', 'Expense V2'),
('CHI_3_the', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_3_the.png', 'Expense V2'),
('CHI_4_lai_tiet_kiem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_4_lai_tiet_kiem.png', 'Expense V2'),
('CHI_4_sua_chua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_4_sua_chua.png', 'Expense V2'),
('CHI_4_sua_chua_nha_cua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_4_sua_chua_nha_cua.png', 'Expense V2'),
('CHI_5_bieu_tang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_5_bieu_tang.png', 'Expense V2'),
('CHI_5_dung_cu_hoc_tap', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_5_dung_cu_hoc_tap.png', 'Expense V2'),
('CHI_5_duoc_cho_tang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_5_duoc_cho_tang.png', 'Expense V2'),
('CHI_5_hieu_hi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_5_hieu_hi.png', 'Expense V2'),
('CHI_5_hoc_hanh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_5_hoc_hanh.png', 'Expense V2'),
('CHI_5_hoc_phi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_5_hoc_phi.png', 'Expense V2'),
('CHI_5_ngoai_khoa', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_5_ngoai_khoa.png', 'Expense V2'),
('CHI_5_sach_vo', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_5_sach_vo.png', 'Expense V2'),
('CHI_6_kham_chua_benh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_6_kham_chua_benh.png', 'Expense V2'),
('CHI_6_sua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_6_sua.png', 'Expense V2'),
('CHI_6_suc_khoe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_6_suc_khoe.png', 'Expense V2'),
('CHI_6_thuoc_men', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_6_thuoc_men.png', 'Expense V2'),
('CHI_7_cho_vay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_7_cho_vay.png', 'Expense V2'),
('CHI_7_luong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_7_luong.png', 'Expense V2'),
('CHI_7_thu_no', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_7_thu_no.png', 'Expense V2'),
('CHI_7_tien_lai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_7_tien_lai.png', 'Expense V2'),
('CHI_7_tien_tieu_vat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_7_tien_tieu_vat.png', 'Expense V2'),
('CHI_7_tra_no', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_7_tra_no.png', 'Expense V2'),
('CHI_8_thue_nha', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_8_thue_nha.png', 'Expense V2'),
('CHI_99_cho', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_99_cho.png', 'Expense V2'),
('CHI_99_meo', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_99_meo.png', 'Expense V2'),
('CHI_99_thu_cung', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_99_thu_cung.png', 'Expense V2'),
('CHI_99_tiet_kiem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_99_tiet_kiem.png', 'Expense V2'),
('CHI_99_vat_nuoi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_99_vat_nuoi.png', 'Expense V2'),
('CHI_9_gia_dinh', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_9_gia_dinh.png', 'Expense V2'),
('CHI_9_khach_san', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_9_khach_san.png', 'Expense V2'),
('CHI_9_ngan_hang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_9_ngan_hang.png', 'Expense V2'),
('CHI_9_nha_cua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_9_nha_cua.png', 'Expense V2'),
('CHI_9_the_chap', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_9_the_chap.png', 'Expense V2'),
('CHI_an_sang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_an_sang.png', 'Expense V2'),
('CHI_an_toi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_an_toi.png', 'Expense V2'),
('CHI_an_trua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_an_trua.png', 'Expense V2'),
('CHI_chuyen_khoan', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_chuyen_khoan.png', 'Expense V2'),
('CHI_khac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_khac.png', 'Expense V2'),
('CHI_ma_chay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_ma_chay.png', 'Expense V2'),
('CHI_ngan_hang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_ngan_hang.png', 'Expense V2'),
('CHI_phi_chuyen_khoan', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_phi_chuyen_khoan.png', 'Expense V2'),
('CHI_tien_ra', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_tien_ra.png', 'Expense V2'),
('CHI_UnKnow', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/CHI/CHI_UnKnow.png', 'Expense V2'),
('THU_bao_hiem_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_bao_hiem_xe.png', 'Income V2'),
('THU_bao_hiem_y_te', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_bao_hiem_y_te.png', 'Income V2'),
('THU_bieu_tang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_bieu_tang.png', 'Income V2'),
('THU_cho_vay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_cho_vay.png', 'Income V2'),
('THU_dau_tu', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_dau_tu.png', 'Income V2'),
('THU_dich_vu_sinh_hoat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_dich_vu_sinh_hoat.png', 'Income V2'),
('THU_di_vay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_di_vay.png', 'Income V2'),
('THU_duoc_cho_tang', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_duoc_cho_tang.png', 'Income V2'),
('THU_hieu_hi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_hieu_hi.png', 'Income V2'),
('THU_hoc_phi', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_hoc_phi.png', 'Income V2'),
('THU_khac', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_khac.png', 'Income V2'),
('THU_lai_tiet_kiem', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_lai_tiet_kiem.png', 'Income V2'),
('THU_luong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_luong.png', 'Income V2'),
('THU_nha_cua', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_nha_cua.png', 'Income V2'),
('THU_rua_xe', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_rua_xe.png', 'Income V2'),
('THU_sinh_hoat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_sinh_hoat.png', 'Income V2'),
('THU_the', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_the.png', 'Income V2'),
('THU_the_chap', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_the_chap.png', 'Income V2'),
('THU_thue_nha', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_thue_nha.png', 'Income V2'),
('THU_thuong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_thuong.png', 'Income V2'),
('THU_thu_no', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_thu_no.png', 'Income V2'),
('THU_tien_lai', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_tien_lai.png', 'Income V2'),
('THU_tien_tieu_vat', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_tien_tieu_vat.png', 'Income V2'),
('THU_tien_vao', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_tien_vao.png', 'Income V2'),
('THU_tra_no', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_tra_no.png', 'Income V2'),
('THU_UnKnow', 'https://storage.googleapis.com/viet-duc-bucket/ICON/V2/THU/THU_UnKnow.png', 'Income V2'),

-- Bank
INSERT INTO icons (name, url, type) VALUES
('Abbank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Abbank.png', 'Bank'),
('ACB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/ACB.png', 'Bank'),
('ANZ', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/ANZ.png', 'Bank'),
('Argibank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Argibank.png', 'Bank'),
('Bac_A_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Bac_A_Bank.png', 'Bank'),
('Bangkok_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Bangkok_Bank.png', 'Bank'),
('Bank_of_China', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Bank_of_China.png', 'Bank'),
('Baoviet_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Baoviet_Bank.png', 'Bank'),
('BIDC', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/BIDC.png', 'Bank'),
('Bidv', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Bidv.png', 'Bank'),
('Cake_by_VPBank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Cake_by_VPBank.png', 'Bank'),
('Cathay_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Cathay_Bank.png', 'Bank'),
('CB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/CB.png', 'Bank'),
('Chase_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Chase_Bank.png', 'Bank'),
('CIMB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/CIMB.png', 'Bank'),
('Citibank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Citibank.png', 'Bank'),
('Commonwealth_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Commonwealth_Bank.png', 'Bank'),
('Deutsche_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Deutsche_Bank.png', 'Bank'),
('DongA_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/DongA_Bank.png', 'Bank'),
('DSB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/DSB.png', 'Bank'),
('Eximbank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Eximbank.png', 'Bank'),
('GPBank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/GPBank.png', 'Bank'),
('HDBank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/HDBank.png', 'Bank'),
('Hong_Leong_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Hong_Leong_Bank.png', 'Bank'),
('Hsbc', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Hsbc.png', 'Bank'),
('Industrial_Bank_of_Korea', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Industrial_Bank_of_Korea.png', 'Bank'),
('IVB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/IVB.png', 'Bank'),
('KB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/KB.png', 'Bank'),
('KEB_Hana_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/KEB_Hana_Bank.png', 'Bank'),
('KienLong_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/KienLong_Bank.png', 'Bank'),
('Lienviet_PostBank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Lienviet_PostBank.png', 'Bank'),
('Maybank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Maybank.png', 'Bank'),
('MB_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/MB_Bank.png', 'Bank'),
('Mega_International_Commercial_Ban', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Mega_International_Commercial_Bank.pn', 'Bank'),
('Mizuho', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Mizuho.png', 'Bank'),
('MSB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/MSB.png', 'Bank'),
('Nam_A_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Nam_A_Bank.png', 'Bank'),
('Napas', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Napas.png', 'Bank'),
('NCB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/NCB.png', 'Bank'),
('OCB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/OCB.png', 'Bank'),
('Ocean_bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Ocean_bank.png', 'Bank'),
('PG_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/PG_Bank.png', 'Bank'),
('Public_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Public_Bank.png', 'Bank'),
('PVcom_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/PVcom_Bank.png', 'Bank'),
('SCB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/SCB.png', 'Bank'),
('Scotiabank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Scotiabank.png', 'Bank'),
('SeA_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/SeA_Bank.png', 'Bank'),
('SHB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/SHB.png', 'Bank'),
('Shinhan_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Shinhan_Bank.png', 'Bank'),
('SMFG', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/SMFG.png', 'Bank'),
('Standard_Chartered', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Standard_Chartered.png', 'Bank'),
('Techcombank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Techcombank.png', 'Bank'),
('Timo', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Timo.png', 'Bank'),
('TPBank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/TPBank.png', 'Bank'),
('Tyme', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Tyme.png', 'Bank'),
('TymeBank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/TymeBank.png', 'Bank'),
('UBSP', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/UBSP.png', 'Bank'),
('VIB', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/VIB.png', 'Bank'),
('Vietcombank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Vietcombank.png', 'Bank'),
('VietinBank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/VietinBank.png', 'Bank'),
('Viet_A_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Viet_A_Bank.png', 'Bank'),
('Viet_Capital_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Viet_Capital_Bank.png', 'Bank'),
('VPBank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/VPBank.png', 'Bank'),
('Woori_Bank', 'https://storage.googleapis.com/viet-duc-bucket/ICON/BANK/Woori_Bank.png', 'Bank');

-- E-Wallet
INSERT INTO icons (name, url, type) VALUES
('Apota', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Apota.png' ,'E-Wallet'),
('Baokim', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Baokim.png' ,'E-Wallet'),
('ECPay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/ECPay.png' ,'E-Wallet'),
('GrabPay_by_Moca', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/GrabPay_by_Moca.png' ,'E-Wallet'),
('Moca', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Moca.png' ,'E-Wallet'),
('Momo', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Momo.png' ,'E-Wallet'),
('Nextpay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Nextpay.png' ,'E-Wallet'),
('Ngan_luong', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Ngan_luong.png' ,'E-Wallet'),
('PayME', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/PayME.png' ,'E-Wallet'),
('Payoo', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Payoo.png' ,'E-Wallet'),
('ShopeePay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/ShopeePay.png' ,'E-Wallet'),
('Truemoney', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Truemoney.png' ,'E-Wallet'),
('Viettel_Money', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Viettel_Money.png' ,'E-Wallet'),
('Viettel_Pay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Viettel_Pay.png' ,'E-Wallet'),
('Vimo', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Vimo.png' ,'E-Wallet'),
('VinID', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/VinID.png' ,'E-Wallet'),
('VNPay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/VNPay.png' ,'E-Wallet'),
('VNPay_Money', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/VNPay_Money.png' ,'E-Wallet'),
('VTCPay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/VTCPay.png' ,'E-Wallet'),
('Zalopay', 'https://storage.googleapis.com/viet-duc-bucket/ICON/E_WALLET/Zalopay.png' ,'E-Wallet');

